from icecube import icetray
import os


@icetray.traysegment
def CalibrateSLCs(tray, name, Config=os.environ['I3_BUILD']+'/tpx/slc_calib_parameters.pcl',
                  Launches = "IceTopRawData",
                  SLCVEMPulses = "OfflineIceTopSLCVEMPulses",
                  SLCTankPulses = "OfflineIceTopSLCTankPulses"):
    """
    This extracts and calibrates SLC pulses. The current
    implementation needs to know the ATWD channel used and therefore
    needs access to the waveforms generated by
    I3WaveformSplitter. Since these are discarded, they have to be
    produced again (hence this segment).

    The current implementation of SLC calibration is done after VEM
    calibration. The proper place to do it would be in
    level2_CalibrateAndExtractPulses.CalibrateAndExtractIceTop.

    This segment also includes 'merging' the SLC pulses into the tank
    pulses container.
    """

    Waveforms = 'CalibratedIceTopWaveforms'
    SLCWaveforms = 'CalibratedIceTopATWD_SLC'

    from icecube import topeventcleaning, tpx, WaveCalibrator

    # get the waveforms
    tray.AddModule('I3WaveCalibrator', name + 'CalibrateIceTop',
                   Launches = Launches,
                   Waveforms = Waveforms,
                   WaveformRange = 'IgnoreThisWaveformRange',
                   Errata = 'IgnoreThisErrata',
                   If = lambda fr: Launches in fr,
                   )

    tray.AddModule('I3WaveformSplitter', name + 'IceTopSplitter',
                   Input = Waveforms,
                   HLC_ATWD = 'RedundantHLCATWDWaveforms',
                   HLC_FADC = 'RedundantHLCFADCWaveforms',
                   SLC = SLCWaveforms,
                   Force = True, # ! put all maps in the frame, even if they are empty
                   PickUnsaturatedATWD = True,  # ! do not keep all ATWDs, but only the highest non-saturated gain one
                   If = lambda fr: Launches in fr,
                   )

    tray.AddModule('Delete', name + '_remove_redundant',
                   Keys=['RedundantHLCATWDWaveforms', 'RedundantHLCFADCWaveforms',
                         'IgnoreThisWaveformRange', 'IgnoreThisErrata'])

    # do the calibration
    tray.AddModule(tpx.I3IceTopSLCCalibrator, name + 'I3IceTopSLCCalibrator',
                   SLCPulses = SLCVEMPulses,
                   SLCPulsesOut = SLCVEMPulses + 'Calibrated',
                   InputWaveforms = SLCWaveforms,
#                   If = lambda fr: Launches in fr,
                   Config=Config
                   )

    # merge into 'tank' pulses
    tray.AddModule('I3HLCTankPulseMerger', name + 'I3TopTankPulseMerger_SLC',
                   InputVEMPulses = SLCVEMPulses + 'Calibrated',
                   OutputTankPulses = SLCTankPulses,
                   ExcludedTanks = 'TankPulseMergerExcludedSLCTanks'
                   )

del os
